[package]
name = "music"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {git = "https://github.com/iced-rs/iced.git" , features = ["tokio", "advanced"]}
rustube = "0.6.0"
image = "0.25.1"
serde_json = "1"
rusqlite = { version = "0.29.0", features = ["bundled"] }