[package]
name = "updater"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", features = ["tokio"] }
tokio = { version = "1.38", features = ["fs", "process"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.117"